[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }  # Async runtime
axum = "0.7"                                    # Web framework
hyper = { version = "0.14", features = ["server", "tcp"] } # HTTP server


